# Generated by Django 5.0.6 on 2024-08-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dosage_form',
            new_name='product_type',
        ),
    ]
