# Generated by Django 5.0.6 on 2024-08-17 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
