# Generated by Django 5.0.6 on 2024-08-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_product_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_name',
            new_name='brand',
        ),
    ]
