# Generated by Django 5.0.6 on 2024-09-12 09:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_rename_brand_name_product_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoldItem",
            fields=[
                ("sold_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity_sold", models.IntegerField()),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sale_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sold_items",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
