# Generated by Django 5.0.6 on 2024-07-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_owner_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='username',
        ),
    ]
