# Generated by Django 5.0.6 on 2024-07-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_owner_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='license',
            field=models.URLField(blank=True, null=True),
        ),
    ]
