# Generated by Django 5.0.6 on 2024-08-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_owner_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='avatar',
            field=models.ImageField(blank=True, default='static/assets/illus/default-avatar.png', null=True, upload_to=''),
        ),
    ]
