# Generated by Django 5.1.2 on 2024-10-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0013_alter_owner_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={},
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['email'], name='user_owner_email_d5384e_idx'),
        ),
    ]
