# Generated by Django 5.1.2 on 2025-04-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_owner_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='username',
        ),
    ]
