# Generated by Django 5.1.2 on 2025-04-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_owner_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='shop_name',
            new_name='business_name',
        ),
        migrations.AddField(
            model_name='owner',
            name='business_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
