# Generated by Django 5.1.2 on 2024-12-31 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_sale_date_solditem_sell_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cutomer_name', models.CharField(max_length=100)),
                ('cutomer_age', models.CharField(max_length=3, null=True)),
                ('cutomer_gender', models.CharField(max_length=6, null=True)),
                ('cutomer_doctor', models.CharField(max_length=100, null=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
