# Generated by Django 5.1.2 on 2025-01-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_bill_billingitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cutomer_age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cutomer_doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cutomer_gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
