# Generated by Django 5.1.2 on 2025-01-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_customer_cutomer_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cutomer_name',
            new_name='customer_name',
        ),
    ]
