# Generated by Django 5.1.2 on 2025-01-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_cutomer_name_customer_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cutomer_age',
            new_name='customer_age',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cutomer_doctor',
            new_name='customer_doctor',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cutomer_gender',
            new_name='customer_gender',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
