# Generated by Django 5.0.6 on 2024-07-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_owner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
