# Generated by Django 5.0.6 on 2024-07-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_owner_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='owner',
            managers=[
            ],
        ),
    ]
