# Generated by Django 5.0.6 on 2024-07-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_rename_user_medicines_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicines',
            old_name='user_name',
            new_name='email',
        ),
    ]
