# Generated by Django 5.0.6 on 2024-07-20 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_rename_user_name_medicines_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicines',
            old_name='email',
            new_name='owner_id',
        ),
    ]
