# Generated by Django 5.0.6 on 2024-07-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_rename_email_medicines_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicines',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
